name: Snyk Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Krävs för att kunna ladda upp SARIF till Code Scanning
permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: snyk-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snyk:
    name: snyk
    runs-on: ubuntu-24.04
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pinnar till din använda commit för reproducerbarhet
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        with:
          snyk-version: latest

      # --- Snyk Code (SAST) ---
      # Kör bara om det finns kodfiler; stoppa inte pipelinen vid fel/entitlements.
      - name: Snyk Code test (SARIF)
        id: snyk_code
        if: ${{ hashFiles('**/*.js','**/*.jsx','**/*.ts','**/*.tsx','**/*.py','**/*.java','**/*.cs','**/*.go','**/*.rb','**/*.php','**/*.kt','**/*.swift') != '' }}
        continue-on-error: true
        run: |
          snyk code test --sarif --sarif-file-output=snyk-code.sarif

      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      # --- Snyk Open Source (SCA) ---
      # Kör bara om det finns kända manifest; stoppa inte pipelinen vid findings/fel.
      - name: Snyk Open Source monitor
        if: ${{ always() && (
              hashFiles('package.json','package-lock.json','yarn.lock','pnpm-lock.yaml',
                        'requirements.txt','poetry.lock','Pipfile.lock',
                        'pom.xml','build.gradle','build.gradle.kts',
                        'Gemfile.lock','go.mod','Cargo.toml',
                        'composer.lock','*.csproj','*.fsproj') != ''
            ) }}
        continue-on-error: true
        run: |
          snyk monitor --all-projects

      # --- Snyk IaC ---
      # Kör bara om repo:t ser ut att innehålla IaC (Terraform/YAML); stoppa inte pipelinen vid fel.
      - name: Snyk IaC test
        if: ${{ always() && (
              hashFiles('**/*.tf') != '' ||
              hashFiles('**/*.yml') != '' ||
              hashFiles('**/*.yaml') != ''
            ) }}
        continue-on-error: true
        run: |
          snyk iac test

      # --- Container (frivilligt) ---
      - name: Build Docker image
        if: ${{ always() && (hashFiles('Dockerfile','**/Dockerfile') != '') }}
        run: |
          docker build -t local/app:${{ github.sha }} .

      - name: Snyk Container monitor
        if: ${{ always() && (hashFiles('Dockerfile','**/Dockerfile') != '') }}
        continue-on-error: true
        run: |
          snyk container monitor local/app:${{ github.sha }}
